export const contactList = [
  {
    id: "u1",
    name: "Manraj singh",
    profilePic: "/profile/pp1.png",
    lastText: "did you complete skill tests?",
    lastTextTime: "12:58 PM",
    online: "last seen 5 mins ago",
  },
  {
    id: "u2",
    name: "MJ",
    profilePic: "/profile/pp1.png",
    lastText: `yes,received mail yesterday itself`,
    lastTextTime: "12:45 PM",
    online: "online",
  },
  {
    id: "u3",
    name: "Sahil",
    profilePic: "/profile/pp2.png",
    lastText: "baba lets go out?",
    lastTextTime: "12:30 PM",
    online: "last seen yesterday",
  },
  {
    id: "u4",
    name: "Rahul",
    profilePic: "/profile/pp3.jpeg",
    lastText: "",
    lastTextTime: "12:00 PM",
    online: "online",
  },
];

export const messagesList = {
  u1: [
    {
      id: 1,
      messageType: "TEXT",
      text: "hello",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "What's up?",
      senderID: "u1",
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: "u1",
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "did you complete skill tests?",
      senderID: "u1",
      addedOn: "12:00 PM",
    },
  ],
  u2: [
    {
      id: 1,
      messageType: "TEXT",
      text: "hello",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "What's up?",
      senderID: "u2",
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "heard u got placed in google?",
      senderID: "u2",
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "yes,received mail yesterday itself",
      senderID: 0,
      addedOn: "12:00 PM",
    },
  ],
  u3: [
    {
      id: 1,
      messageType: "TEXT",
      text: "hey,congrats",
      senderID: "u3",
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "Thanks man",
      senderID: 0,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "baba lets go out?",
      senderID: "u3",
      addedOn: "12:00 PM",
    },
  ],
};
